plugins {
    id "com.android.application"
    id "com.chaquo.python"
}

android {
    namespace "com.lanp2pchat"
    compileSdk 35

    defaultConfig {
        applicationId "com.lanp2pchat"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "0.1"

        python {
            buildPython "python3.10"

            pip {
                install "fastapi==0.95.2"
                install "starlette==0.27.0"
                install "pydantic==1.10.13"
                install "uvicorn==0.22.0"
                install "aiosqlite"
                install "requests"
                install "websockets"
            }
        }

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    // Задаем зависимости между задачами
    tasks.whenTaskAdded { task ->
        // Задача для установки Python зависимостей
        if (task.name == 'installDebugPythonRequirements') {
            task.dependsOn 'mergeDebugNativeDebugMetadata' // Устанавливаем зависимость от mergeDebugNativeDebugMetadata
        }

        // Задача для объединения Python исходных файлов
        if (task.name == 'mergeDebugPythonSources') {
            task.dependsOn 'installDebugPythonRequirements' // Устанавливаем зависимость от installDebugPythonRequirements
        }
    }

    sourceSets {
        main {
            python {
                // Подключаем Python-код из корня проекта
                srcDir "../../"
            }

            assets {
                // Кладем содержимое static/ в Android assets
                srcDirs "../../static"
            }
        }
    }
}